-- 1. TẠO BẢNG KHOA (Departments)
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) PRIMARY KEY 
    TenKhoa NVARCHAR(100) NOT NULL UNIQUE 
    DienThoai VARCHAR(15) UNIQUE 
    DiaChiVanPhong NVARCHAR(255) 
);

-- 2. TẠO BẢNG GIANG_VIEN (Lecturers)
CREATE TABLE GIANG_VIEN (
    MaGV INT PRIMARY KEY AUTO_INCREMENT 
    HoTen NVARCHAR(100) NOT NULL 
    GioiTinh BOOLEAN NOT NULL 
    NgaySinh DATE 
    HocVi NVARCHAR(50) 
    Email VARCHAR(100) UNIQUE NOT NULL 
    MaKhoa VARCHAR(10),
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa) ON DELETE SET NULL ??
);

-- 3. TẠO BẢNG SINH_VIEN (Students)
CREATE TABLE SINH_VIEN (
    MaSV VARCHAR(10) PRIMARY KEY 
    HoTen NVARCHAR(100) NOT NULL 
    NgaySinh DATE NOT NULL 
    GioiTinh BOOLEAN NOT NULL 
    DiaChi NVARCHAR(255) 
    SoDienThoai VARCHAR(15) UNIQUE 
    Email VARCHAR(100) UNIQUE NOT NULL 
    NamNhapHoc YEAR NOT NULL 
    MaKhoa VARCHAR(10),
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa) ON DELETE RESTRICT 
);

-- 4. TẠO BẢNG MON_HOC (Courses)
CREATE TABLE MON_HOC (
    MaMH VARCHAR(10) PRIMARY KEY 
    TenMH NVARCHAR(100) NOT NULL UNIQUE 
    SoTinChi INT NOT NULL CHECK (SoTinChi > 0) 
    MaGV INT,
    FOREIGN KEY (MaGV) REFERENCES GIANG_VIEN(MaGV) ON DELETE SET NULL 
);

-- 5. TẠO BẢNG DANG_KY (Enrollments)
CREATE TABLE DANG_KY (
    MaSV VARCHAR(10),
    MaMH VARCHAR(10),
    HocKy INT NOT NULL CHECK (HocKy BETWEEN 1 AND 3) 
    NamHoc YEAR NOT NULL 
    NgayDangKy DATE DEFAULT (CURRENT_DATE()) 
    PRIMARY KEY (MaSV, MaMH, HocKy, NamHoc), -- Khóa chính kép
    FOREIGN KEY (MaSV) REFERENCES SINH_VIEN(MaSV) ON DELETE CASCADE,
    FOREIGN KEY (MaMH) REFERENCES MON_HOC(MaMH) ON DELETE RESTRICT
);

-- 6. TẠO BẢNG DIEM_SO (Scores)
CREATE TABLE DIEM_SO (
    MaSV VARCHAR(10),
    MaMH VARCHAR(10),
    HocKy INT NOT NULL,
    NamHoc YEAR NOT NULL,
    DiemChuyenCan DECIMAL(4, 2) CHECK (DiemChuyenCan BETWEEN 0 AND 10) 
    DiemGiuaKy DECIMAL(4, 2) CHECK (DiemGiuaKy BETWEEN 0 AND 10) 
    DiemCuoiKy DECIMAL(4, 2) CHECK (DiemCuoiKy BETWEEN 0 AND 10) 
    DiemTongKet DECIMAL(4, 2) 
    TrangThai NVARCHAR(20) 
    PRIMARY KEY (MaSV, MaMH, HocKy, NamHoc),
    FOREIGN KEY (MaSV, MaMH, HocKy, NamHoc) REFERENCES DANG_KY(MaSV, MaMH, HocKy, NamHoc) ON DELETE CASCADE
);
